from decouple import config


ENERGINET_OPENAI_ENDPOINT = config('ENERGINET_OPENAI_ENDPOINT')
ENERGINET_OPENAI_KEY = config('ENERGINET_OPENAI_KEY')
ENERGINET_DEPLOYMENT_NAME = config('ENERGINET_DEPLOYMENT_NAME')
ENERGINET_API_VERSION = config('ENERGINET_API_VERSION', default='2023-05-15')
